### PR TITLE
Added Flutter project to the repository 

### PR DESCRIPTION
**Pull request by SirPaws**
I just put them in a folder called frontend, but I can change it to something else if need be.

also, it might need a bit of refactoring, but right now I just put it up as is, so everyone else can see what is happening

### CODE REVIEW

**Comment by spralja** [comment]
@SirPaws Are you sure all of this should be in git. Is it possible that some of the files are created when building?
Seems like a lot of files.

**Comment by SirPaws** [comment]
> @SirPaws Are you sure all of this should be in git. Is it possible that some of the files are created when building? Seems like a lot of files.

Yeah, flutter automatically sets up a .gitignore for the files and directories that it believes should or shouldn't be included

**Comment by spralja** [comment]
@SirPaws what kind of OS are you using. Because I'm reading that flutter isn't available on wsl.

**Comment by spralja** [comment]
@SirPaws I'm reconsidering having the fronted and backend in different repos. 

As it is right now I think that the backend will be just a REST api.

**Comment by SirPaws** [comment]
> @SirPaws what kind of OS are you using. Because I'm reading that flutter isn't available on wsl.

I'm on windows, but it should be supported by all the major platforms, as for WSL it's probably not supported but I would assume it would work without errors on Win11 at least
> I'm reconsidering having the fronted and backend in different repos.

Sure I honestly don't mind either way, If you feel like it would be easier to manage if they were separate, I can make a new repo for this

**Comment by spralja** [comment]
> Sure I honestly don't mind either way, If you feel like it would be easier to manage if they were separate, I can make a new repo for this

@SirPaws I think that would be best

**Comment by SirPaws** [comment]
Okay so I've gone ahead and made a repository for [the frontend](https://github.com/SirPaws/pychart-ruc-frontend)
and everyone should hopefully have been invited to it

**Pull request closed without merging**
